@startuml
|사용자|
start
:스터디 개설 버튼 클릭;

|시스템|
:스터디 개설 화면 출력;

if(클릭) then(개설하기)
   |참가자|
   :스터디 정보 입력;
   |시스템|
   :스터디 정보 등록 요청;
   |DB|
   :스터디 정보 등록;
   |시스템|
   :스터디 개설 완료 메시지 창 출력;
else(취소)
endif
|시스템|
:기존화면 출력;
stop
@enduml