@startuml
|개설자|
start
:스터디 관리 버튼 클릭;

|시스템|
:스터디 관리 페이지 출력;

if(버튼 클릭) then (스터디 삭제)
   |시스템|
   :스터디 삭제 확인 창 출력;
   if(확인) then (예)
      |시스템|
      :스터디 삭제 요청;
      |DB|
      :스터디 정보 삭제;
      |시스템|
      fork
         :삭제 완료 메시지 창 출력;
      fork again
         :참가자 스터디 삭제 쪽지 전송 요청;
         |DB|
         :쪽지 전송;
         |시스템|
      end fork
   else (아니오)
   endif
else
   |개설자|
   :스터디 수정 정보 입력;
   |시스템|
   :스터디 정보 수정 요청;
   |DB|
   :스터디 정보 수정;
   |시스템|
   :수정 완료 메시지 창 출력;
endif
stop
@enduml