@startuml
|개설자|
start
:참가자 관리 버튼 클릭;

|시스템|
:추방 버튼 활성화;

|개설자|
:추방 버튼 클릭;

|시스템|
:추방 확인 창 출력;

if(확인) then(예)
   |시스템|
   :참가자 추방 요청;
   |DB|
   :참가자 정보 삭제;
   |시스템|
   :참가자 추방 완료 메시지창 출력 및 추방자 시스템 쪽지 전송 요청;
   |DB|
   :추방자 시스템 쪽지 전송;
else (아니오)
endif
stop
@enduml