@startuml

start
:쪽지 시스템;
:쪽지 보관함 정보 출력;

if(메세지 삭제) then (Y)
    :삭제 메시지 선택;
    :삭제 버튼 클릭;
    :메시지 삭제;
else (N)
endif
:사용자 타이틀 클릭;
:주고받은 메시지 확인;
:메시지 입력;
:메시지 전송 버튼 클릭;
:송/수신자 및 메시지 확인;
:수신자 보관함에 반영;
:송신자 보관함에 반영;
stop
@enduml