@startuml
actor "스터디 참가자" as 참가자
participant ":시스템" as 시스템
participant ":DB" as DB

참가자 -> 시스템 : 스터디 탈퇴 버튼 클릭
참가자 <-- 시스템 : 스터디 탈퇴 확인 메시지창 출력

opt '예'를 누름 case
   시스템 -> DB : 참가자 정보 삭제 요청
   DB -> DB : 참가자 정보 삭제
   시스템 <-- DB : 삭제 완료
   참가자 <-- 시스템 : 스터디 탈퇴 완료 메시지창 출력
end

@enduml