@startuml
actor "사용자" as 사용자
participant ":시스템" as 시스템
participant ":DB" as DB

사용자 -> 시스템 : 스터디 개설 버튼 클릭
사용자 <-- 시스템 : 스터디 개설 화면 출력

opt '개설하기' 버튼을 누르기 전에 '취소' 버튼을 누름 case
   사용자 <-- 시스템 : 개설 취소 확인 메시지창 출력
   opt '예' 버튼을 누름 case
      사용자 <-- 시스템 : 기존 화면으로 복귀
   end
end

사용자 -> 시스템 : 스터디 정보 입력 후 개설하기 버튼 클릭
시스템 -> DB : 스터디 정보 등록 요청
DB -> DB : 스터디 정보 등록
시스템 <-- DB : 스터디 정보 등록 완료
사용자 <-- 시스템 : 스터디 개설 완료 메시지창 출력
@enduml