@startuml
actor "스터디 개설자" as 개설자
participant ":시스템" as 시스템
participant ":DB" as DB

개설자 -> 시스템 : '스터디 관리' 버튼 클릭
개설자 <-- 시스템 : 스터디 관리 페이지 출력
alt '스터디 삭제' 버튼 클릭
   개설자 -> 시스템 : '스터디 삭제' 버튼 클릭
   개설자 <-- 시스템 : 스터디 삭제 확인 창 출력
   opt '예' 버튼 클릭시
      개설자 -> 시스템 : '예' 버튼 클릭
      시스템 -> DB : 스터디 삭제 요청
      DB -> DB : 스터디 삭제
      시스템 <-- DB : 스터디 삭제 완료
      시스템 -> DB : 삭제 소식 쪽지 전송 요청
      DB -> DB : 삭제 소식 쪽지 전송
      시스템 <-- DB : 쪽지 전송 완료
      개설자 <-- 시스템 : 삭제 완료 메시지 창 출력 및 스터디 초기 화면 출력
   end

else
   개설자 -> 시스템 : 스터디 정보 수정
   시스템 -> DB : 수정된 스터디 정보 갱신 요청
   DB -> DB : 스터디 정보 갱신
   시스템 <-- DB : 스터디 정보 갱신 완료
   개설자 <-- 시스템 : 수정 완료 메시지 창 출력
end
@enduml