@startuml
actor "스터디 개설자" as 개설자
participant ":시스템" as 시스템
participant ":DB" as DB

개설자 -> 시스템 : '공간 대관' 버튼 클릭
개설자 <-- 시스템 : 공간 대관 페이지 출력

alt '세미나실 대관' 버튼 클릭시
   개설자 -> 시스템 : '세미나실 대관' 버튼 클릭
   개설자 <-- 시스템 : 세미나실 대관 사이트 출력
   개설자 -> 시스템 : 대관 장소 입력
   시스템 -> DB : 참가자들에게 대관 장소 쪽지 전송 요청
   DB -> DB : 쪽지 전송
   시스템 <-- DB : 쪽지 전송 완료
   개설자 <-- 시스템 : 완료 메시지창 출력 및 기존 페이지 복귀

else '도서관 대관' 버튼 클릭시
   개설자 -> 시스템 : '도서관 대관' 버튼 클릭
   개설자 <-- 시스템 : 도서관 대관 사이트 출력
   개설자 -> 시스템 : 대관 장소 입력
   시스템 -> DB : 참가자들에게 대관 장소 쪽지 전송 요청
   DB -> DB : 쪽지 전송
   시스템 <-- DB : 쪽지 전송 완료
   개설자 <-- 시스템 : 완료 메시지창 출력 및 기존 페이지 복귀
end
@enduml