@startuml
actor "스터디 개설자" as 개설자
participant ":시스템" as 시스템
participant ":DB" as DB

개설자 -> 시스템 : '참가자 관리' 버튼 클릭
개설자 <-- 시스템 : '추방' 버튼 활성화
opt '추방' 버튼 클릭시
   개설자 -> 시스템 : '추방' 버튼 클릭
   개설자 <-- 시스템 : 추방 확인 창 출력
   opt '예' 버튼 클릭시
      개설자 -> 시스템 : '예' 버튼 클릭
      시스템 -> DB : 참가자 추방 요청
      DB -> DB : 참가자 추방
      시스템 <-- DB : 참가자 추방 완료
      개설자 <-- 시스템 : 참가자 추방 완료 메시지창 출력
   end
end
@enduml