@startuml
left to right direction
:사용자: --> (참가자 조회)
:사용자: --> (스터디 참가)
:사용자: --> (스터디 조회)
:사용자: --> (스터디 개설)
:사용자: <|-- :스터디 개설자:
:사용자: <|-- :스터디 참가자:
:스터디 참가자: --> (스터디 탈퇴)
:스터디 개설자: --> (장소 대관)
:스터디 개설자: --> (스터디 관리)
:스터디 개설자: --> (참가자 관리)
@enduml