@startuml
hide empty description

[*] --> 쪽지보관함로딩: 쪽지 버튼 클릭
쪽지보관함로딩 -> 쪽지로그로딩: 쪽지 타이틀 클릭
쪽지로그로딩 -> 메시지입력대기: 쪽지 로딩 완료
메시지입력대기 -> 메시지전송대기: 메시지 입력 완료
메시지전송대기 -> 메시지전송확인: 메시지 전송버튼 클릭
메시지전송확인 -> 메시지전송완료: 확인버튼 클릭
메시지전송완료 --> [*]
@enduml