@startuml
hide empty description
left to right direction

state "관리 준비" as 준비
state "관리 준비 중" as 준비중
state "수정 가능" as 가능
state "수정 확인" as 확인
state "삭제 확인" as 삭제확인
state "삭제 중" as 삭제중
state "삭제 완료" as 삭제완료
state "수정 완료" as 완료


[*] --> 준비 : <<스터디 관리 버튼 클릭>>
준비 --> 준비중 : <<스터디 관리 페이지 출력>>
준비중 --> 삭제확인 : <<스터디 삭제 버튼 클릭>>
삭제확인 --> 삭제중 : <<스터디 정보 삭제>>
삭제중 --> 삭제완료 : <<삭제 완료 메시지 창 출력 및 쪽지 전송>>
삭제완료 --> [*]
준비중 --> 가능 : <<스터디 정보 수정>>
가능 --> 확인 : <<수정하기 버튼 클릭>>
확인 --> 완료 : <<스터디 정보 수정>>
완료 --> [*]
@enduml