@startuml
hide empty description
left to right direction

state "추방 준비" as 준비
state "추방 준비 중" as 준비중
state "추방 가능" as 가능
state "추방 확인" as 확인
state "추방 중" as 중
state "추방 완료" as 완료


[*] --> 준비 : <<참가자 관리 버튼 클릭>>
준비 --> 준비중 : <<추방 버튼 활성화>>
준비중 --> 가능 : <<추방 버튼 클릭>>
가능 --> 확인 : <<예 버튼 클릭>>
가능 --> [*] : <<아니오 버튼 클릭>>
확인 --> 중 : <<참가자 정보 삭제>>
중 --> 완료 : <<추방 완료 메시지창 출력 및 쪽지 전송>>
완료 --> [*]
@enduml