@startuml
hide empty description
left to right direction

state "조회 확인" as 확인
state "조회 중" as 중
state "조회 완료" as 완료


[*] --> 확인 : <<참가자 조회 버튼 클릭>>
확인 --> 중 : <<참가자 정보 조회>>
중 --> 완료 : <<참가자 정보 출력>>
완료 --> [*]
@enduml